#
#
#   A Api using demo
#
#

###
# 1. Create user

POST http://127.0.0.1:12345/post/user
content-type: application/json

{
    "operation": "create",
    "username": "test",
    "password": "password1"
}

# return
# { "ID": , "token": }

###
# 2. Login

POST http://127.0.0.1:12345/post/user
content-type: application/json

{
    "operation": "read",
    "username": "test",
    "password": "password1"
}

# return
# { "ID": , "token": }

###
# 3. Update username or password
### password
POST http://127.0.0.1:12345/post/user
content-type: application/json

{
    "ID": 1,
    "token": "123123",
    "operation": "update",
    "password": "password_new",
    "old_password": "password1"
}
### username
POST http://127.0.0.1:12345/post/user
content-type: application/json

{
    "ID": 1,
    "token": "123123",
    "operation": "update",
    "username": "test_new"
}

###
# 4. Delete user
POST http://127.0.0.1:12345/post/user
content-type: application/json

{
    "operation": "delete",
    "ID": 1,
    "token": "123123"
}

###
# 5. Read Source (read from file)
GET http://127.0.0.1:12345/get/source/1

###
# 6. Create Source
POST http://127.0.0.1:12345/post/source
content-type: application/json

{
    "operation": "create",
    "token":"123123",
    "owner":2,
    "name": "src2",
    "magnet": "any:??"
}

###
# 7. Update Source
POST http://127.0.0.1:12345/post/source
content-type: application/json

{
    "operation": "update",
    "ID":,
    "token":,
    "name": "src_changed",
    "magnet": "something"
}

###
# 8. Delete Source
POST http://127.0.0.1:12345/post/source
content-type: application/json

{
    "operation": "delete",
    "ID":,
    "token":
}

###
# 9. Create tag
POST http://127.0.0.1:12345/post/tag
content-type: application/json

{
    "operation": "create",
    "ID":,
    "token": 123123,
    "name": "src"
}

###
# 10. Delete tag
POST http://127.0.0.1:12345/post/tag
content-type: application/json

{
    "operation": "delete",
    "ID":,
    "token": 123123,
    "name": "src"
}

###
# 11. get srcs by user
GET http://127.0.0.1:12345/get/user/1

###
# 12. get tag list
GET http://127.0.0.1:12345/get/taglist

###
# 13. get srcs by tag
GET http://127.0.0.1:12345/get/taglist?=

###
# 14. close server
GET http://127.0.0.1:12345/stop